apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: secure-statements
  labels:
    app.kubernetes.io/name: web-api
    app.kubernetes.io/part-of: secure-statement-delivery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
